FROM ghcr.io/opcal/alpine:latest AS builder

ARG FRP_VERSION

RUN apk --no-cache add curl tar unzip; \
    curl -L https://github.com/fatedier/frp/releases/download/${FRP_VERSION}/frp_$(echo $FRP_VERSION | cut -d 'v' -f 2)_linux_amd64.tar.gz -o /tmp/frp.tar.gz ; \
    tar -xvzf /tmp/frp.tar.gz -C / ; \
    ln -s /frp_$(echo $FRP_VERSION | cut -d 'v' -f 2)_linux_amd64 /frp ; \
    chmod -R 777 /frp/frps

FROM ghcr.io/opcal/alpine:latest

WORKDIR /app

COPY --from=builder /frp/frps /usr/bin

ENTRYPOINT ["/usr/bin/frps"]