name: build-coredns-images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 1 * *"
  push:
    branches: 
      - main
    paths:
      - "coredns/**"
      - ".github/workflows/coredns.yaml"

jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_NAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build & push
        env:
          PROJECT_VERSION: 1.0.0
          TAG_VERSION: ${{ github.run_number }}
          CI_REGISTRY: ghcr.io
          PROJECT_DIR: ${{ github.workspace }}
        run: |
          sudo apt update && sudo apt install curl jq
          chmod +x coredns/coredns.sh
          coredns/coredns.sh
