name: build-sample-images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 1 * *"
  push:
    branches: 
      - main
    paths:
      - "sample/**"
      - ".github/workflows/sample.yaml"
      - ".ci/build-sample.sh"

jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_NAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build & push
        env:
          PROJECT_VERSION: 1.0.0
          TAG_VERSION: ${{ github.run_number }}
          CI_REGISTRY: ghcr.io
          PROJECT_DIR: ${{ github.workspace }}
        run: |
          sudo apt update && sudo apt install curl jq
          chmod +x .ci/build-sample.sh
          .ci/build-sample.sh
