name: build-sample-images

on:
  schedule:
    - cron: "0 6 1 * *"
  push:
    branches: 
      - main
    paths:
      - "sample/**"
      - ".github/workflows/sample.yaml"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build & push
        env:
          PROJECT_VERSION: 1.0.0
          CI_DEPLOY_USER: ${{ secrets.CR_NAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CR_PAT }}
          CI_REGISTRY: ghcr.io
        run: |
          sudo apt update && sudo apt install curl &&
          chmod +x build-bin/build-sample.sh &&
          build-bin/build-sample.sh
