name: test

on:
  push:
    tags: ""
    branches: main
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: main
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: | 
          pwd &&
          ls -la &&
          which docker &&
          docker --version &&
          echo ${GITHUB_ENV} &&
          echo ${GITHUB_ACTOR} &&
          echo ${GITHUB_RUN_NUMBER} &&
          echo ${GITHUB_WORKSPACE} 

   